import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";
import FlyonuiScript from "@/components/FlyonuiScript";
import { AuthContextProvider } from "@/components/context/AuthContext";

const noto = Fira_Sans({
  subsets: ["latin"],
  style: "normal",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-noto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="corporate">
      <body className={`${noto.variable} antialiased`}>
        <Toaster position="top-center" />
        <NextTopLoader />
        <AuthContextProvider>
        {children}
        </AuthContextProvider>
        <FlyonuiScript />
      </body>
    </html>
  );
}