import { type AccordianProps } from "@/components/Accordian";
import appConfig from "@/utills/appConfig";

export const faqData: Record<
  | "generalInfo"
  | "users-patients"
  | "clinics-booking"
  | "medical-reports"
  | "healthcare-providers"
  | "technical",
  AccordianProps["items"]
> = {
  generalInfo: [
    {
      id: "general-info-1",
      title: "What is this AI healthcare platform?",
      desc: "This is an intelligent healthcare assistant that helps users analyze symptoms, receive personalized health tips, locate nearby clinics, book doctor appointments, and access digital medical reports—all in one place.",
    },
    {
      id: "general-info-2",
      title: "Is the service available 24/7?",
      desc: "Yes, the AI assistant and booking features are available 24/7. Doctor availability may vary depending on their individual schedules.",
    },
    {
      id: "general-info-3",
      title: " Is my data safe on this platform?",
      desc: "Absolutely. We use industry-standard encryption and follow healthcare data protection regulations to ensure your information is secure and confidential.",
    },
  ],
  "users-patients": [
    {
      id: "users-patients-1",
      title: "How does the symptom checker work?",
      desc: "Simply input your symptoms into the AI interface. It analyzes your input in real-time using medical data and provides potential causes along with suggested next steps.",
    },
    {
      id: "users-patients-2",
      title: "Are the health tips generated by real doctors?",
      desc: "The health tips are generated by our AI trained on real medical guidelines and reviewed periodically by licensed professionals to ensure accuracy.",
    },
  ],
  "clinics-booking": [
    {
      id: "clinics-booking-1",
      title: "How can I find a nearby clinic?",
      desc: "Enable location services, and the app will suggest nearby clinics based on your location and medical needs.",
    },
    {
      id: "clinics-booking-2",
      title: "Can I book appointments directly through the platform?",
      desc: "Yes, you can view available time slots and book appointments with doctors directly through your dashboard.",
    },
    {
      id: "clinics-booking-3",
      title: "Will I receive a confirmation after booking?",
      desc: "Yes, you’ll get a confirmation via email and in-app notification once the doctor confirms your appointment.",
    },
  ],
  "medical-reports": [
    {
      id: "medial-reports-1",
      title: "Where can I access my medical reports?",
      desc: `All your medical records, prescriptions, and reports are securely stored in your personal dashboard for easy access anytime.`,
    },
    {
      id: "medial-reports-2",
      title: "Can I download or share my medical reports?",
      desc: "es, you can download your reports as PDFs or securely share them with other healthcare providers.",
    },
  ],
  "healthcare-providers": [
    {
      id: "healthcare-providers-1",
      title: "How do I receive appointment requests?",
      desc: `Once a user books an appointment, you’ll get a real-time notification. You can view, accept, or reschedule appointments from your doctor dashboard.`,
    },
    {
      id: "healthcare-providers-2",
      title: "Can I generate and send medical reports through the platform?",
      desc: "Yes, after a consultation, you can create and digitally sign a medical report, which will be automatically shared with the patient.",
    },
    {
      id: "healthcare-providers-3",
      title: "How do I manage my availability?",
      desc: "You can set your working hours, days off, and break times directly in your profile settings to ensure your schedule stays up to date.",
    },
  ],
  technical: [
    {
      id: "technical-1",
      title: "I forgot my password. How can I reset it?",
      desc: "Click on “Forgot Password” on the login page. Follow the instructions to reset it via email.",
    },
    {
      id: "technical-2",
      title: "Who can I contact for technical support?",
      desc: `You can reach our support team via the in-app help center or by emailing ${(
        <a
          href={appConfig.social.email}
          className="link link-hover flex justify-center items-center gap-2 "
        >
          <span className="icon-[tabler--mail] size-5"></span>
          {appConfig.social.email.replace("mailto:", "")}
        </a>
      )}`,
    },
    {
      id: "technical-3",
      title: "Is the app available on mobile devices?",
      desc: "Yes, the platform is fully responsive and also available as a mobile app on iOS and Android.",
    },
  ],
};
